version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run build &&
      npm run start" 
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webclip
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
